### ISSUE TITLE
upsample_nearest2d() takes 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by dengjianbo3** [NVIDIA/retinanet-examples#145]
I train my model and want to transfer .pth model to infer engine .plan model , and I got the result below
I do this in recommanded nvidia docker images

upsample_nearest2d() takes 3 positional arguments but 5 were given

root@cb723caf69d6:/workspace/hostfiles# retinanet export retinanet_rn18fpn.pth test.plan
Loading model from retinanet_rn18fpn.pth...
     model: RetinaNet
  backbone: ResNet18FPN
   classes: 80, anchors: 9
Exporting to ONNX...
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 181, in main
    worker(0, args, 1, model, state)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 164, in worker
    exported = model.export(input_size, args.batch, precision, calibration_files, args.calibration_table, args.verbose, onnx_only=onnx_only)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 224, in export
    torch.onnx.export(self.cuda(), zero_input, onnx_bytes, **extra_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 155, in export
    custom_opsets)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 67, in export
    custom_opsets=custom_opsets)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 467, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 337, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 152, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 186, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 711, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
TypeError: upsample_nearest2d() takes 3 positional arguments but 5 were given (occurred when translating upsample_nearest2d)
[E ProcessGroupNCCL.cpp:284] NCCL watchdog thread terminated

**Comment by yashnv** [comment]
Which container image are you using?

**Comment by yashnv** [comment]
Thanks for reporting this issue. I have pushed updates for Pytorch 20.02 container which fixes this issue.

**Comment by dengjianbo3** [comment]
> Thanks for reporting this issue. I have pushed updates for Pytorch 20.02 container which fixes this issue.

Thanks for the trouble shooting

**Comment by djovanoski** [comment]
> Thanks for reporting this issue. I have pushed updates for Pytorch 20.02 container which fixes this issue.

The issue is still the case even with nvcr.io/nvidia/pytorch:20.02-py3, am i missing something having trained the model using this container and installed retinannet and having same command for converting to .plan
